---
title: "Final Project 204881403-204865687"
output: html_document
date: "2023-02-07"
---

```{r setup, include=FALSE}
library(tidyverse, quietly = T)
library(DESeq2, quietly = T)
library(GEOquery, quietly = T)
```



```{r}

counts <- read.table("./Bulk Data sets/GSE136587_IMSA_BAL_RAW_Counts.txt.gz", header = T, check.names = FALSE,skip =1)
counts
#shorten the column names to be just the sample name without BAL_# at the end, in order to match the metadata
long_names <- colnames(counts)
colnames(counts) <- lapply(X=strsplit(x=long_names, split="_"), FUN=function(x) paste0(head(x, n=1),collapse = "_"))
counts
gse <- getGEO(filename="./Bulk Data sets/GSE136587_series_matrix.txt")
metadata <-as_tibble(gse)
metadata
```
choose columns that we want to compare. Sample, severity, gender, steroid treatment, and age
```{r}
metadata <- metadata %>% 
  dplyr::select(sample = title, severity = characteristics_ch1.1, gender = characteristics_ch1.2, age = characteristics_ch1.3, steroids = characteristics_ch1.4)
metadata
#remove prefixes from data and remove sample that doesn't have info on steroid use
metadata <- metadata[!metadata$steroids == "",]
metadata$gender <- gsub("gender: ","", metadata$gender)
metadata$age <- gsub("age: ", "", metadata$age)
metadata$steroids <-gsub("steroid: ","", metadata$steroids)
metadata$severity <- gsub("asthma degree: ","", metadata$severity)
metadata
```
reorder columns in counts so that it lines up with the metadata, and set disease severity as factor
```{r}

counts <- cbind(GeneID = counts$GeneID, counts[,metadata$sample])
all(metadata$sample == colnames(counts)[-1])
counts
metadata <- mutate(metadata, severity = as.factor(severity))
metadata$severity
```

Now our data is ready to be analyzed with DESeq.
```{r}


```

